#apiVersion: rbac.authorization.k8s.io/v1
#kind: ClusterRole
#metadata:
#  name: gateway-impersonate-lpgprj-sbo-n-vbspdt-gl-02_connect-agent-sa
#  labels:
#    connect.gke.io/owner-feature: connect-gateway
#rules:
#  - apiGroups:
#      - ""
##    resourceNames:
##      - "*"
#    resources:
#      - users
#      - groups
#    verbs:
#      - impersonate
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gateway-cluster-admin-group
subjects:
  - kind: Group
    name: geo-ukraine@voicebase.com
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gateway-impersonate-lpgprj-sbo-n-vbspdt-gl-02_connect-agent-sa
  labels:
    connect.gke.io/owner-feature: connect-gateway
roleRef:
  kind: ClusterRole
  name: gateway-impersonate-lpgprj-sbo-n-vbspdt-gl-02_connect-agent-sa
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: connect-agent-sa
    namespace: gke-connect
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gateway-impersonate-lpgprj-sbo-n-vbspdt-gl-02_edmitrichenko_anthos-bm
  labels:
    connect.gke.io/owner-feature: connect-gateway
rules:
  - apiGroups:
      - ""
    resourceNames:
      - edmitrichenko@liveperson.com
    resources:
      - users
    verbs:
      - impersonate
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gateway-impersonate-lpgprj-sbo-n-vbspdt-gl-02_edmitrichenko_anthos-bm
  labels:
    connect.gke.io/owner-feature: connect-gateway
roleRef:
  kind: ClusterRole
  name: gateway-impersonate-lpgprj-sbo-n-vbspdt-gl-02_edmitrichenko_anthos-bm
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: connect-agent-sa
    namespace: gke-connect
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gateway-permission-lpgprj-sbo-n-vbspdt-gl-02_edmitrichenko_anthos-bm
  labels:
    connect.gke.io/owner-feature: connect-gateway
subjects:
  - kind: User
    name: edmitrichenko@liveperson.com
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
#---
#apiVersion: rbac.authorization.k8s.io/v1
#kind: ClusterRole
#metadata:
#  name: gateway-impersonate-lpgprj-sbo-n-vbspdt-gl-02_skarpenko_anthos-bm
#  labels:
#    connect.gke.io/owner-feature: connect-gateway
#rules:
#  - apiGroups:
#      - ""
#    resourceNames:
#      - skarpenko@liveperson.com
#    resources:
#      - users
#    verbs:
#      - impersonate
#---
#apiVersion: rbac.authorization.k8s.io/v1
#kind: ClusterRoleBinding
#metadata:
#  name: gateway-impersonate-lpgprj-sbo-n-vbspdt-gl-02_skarpenko_anthos-bm
#  labels:
#    connect.gke.io/owner-feature: connect-gateway
#roleRef:
#  kind: ClusterRole
#  name: gateway-impersonate-lpgprj-sbo-n-vbspdt-gl-02_skarpenko_anthos-bm
#  apiGroup: rbac.authorization.k8s.io
#subjects:
#  - kind: ServiceAccount
#    name: connect-agent-sa
#    namespace: gke-connect
#---
#apiVersion: rbac.authorization.k8s.io/v1
#kind: ClusterRoleBinding
#metadata:
#  name: gateway-permission-lpgprj-sbo-n-vbspdt-gl-02_skarpenko_anthos-bm
#  labels:
#    connect.gke.io/owner-feature: connect-gateway
#subjects:
#  - kind: User
#    name: skarpenko@liveperson.com
#roleRef:
#  kind: ClusterRole
#  name: cluster-admin
#  apiGroup: rbac.authorization.k8s.io